var nav_html = {
	'../nav/header.html': '<ul class=" nav  nav-justified  header-nav">'
    +'<li><a href="../bigScreen/submitBusiness.html" class="header-nav-bg1">大屏监控</a></li>'
    +'<li><a href="../businessMonitoring/businessSurvey.html" class="header-nav-bg6">业务监控</a></li>'
    +'<li><a href="../alarmManagement/failureDetect.html" class="header-nav-bg2 ">告警管理</a></li>'
    +'<li><a href="../operationAnalysis/keyBusiness.html" class="header-nav-bg3">运营分析</a></li>'
    +'<li><a href="#" class="header-nav-bg4">运行管理</a></li>'
    +'<li><a href="../configurationManagement/alarmConf.html" class="header-nav-bg5 ">配置管理</a></li>'
+'</ul>',	
	'../nav/bigScreen.html': '<ul class="nav nav-stacked text-center">'
    +'<li>'
        +'<a class="content-left-nav1 noCollapsed collapsed" data-toggle="collapse" href="#serviceStatus">业务状态</a>'
        +'<ul id="serviceStatus" class="nav nav-list collapse secondmenu">'
            +'<li><a class="content-left-nav1-open" href="submitBusiness.html">提交业务</a></li>'
        +'</ul>'
    +'</li>'
	+'<li>'
        +'<a class="content-left-nav2 noCollapsed  collapsed" data-toggle="collapse" href="#systemStatus">系统状态</a>'
        +'<ul id="systemStatus" class="nav nav-list collapse secondmenu">'
            +'<!-- <li><a class="content-left-nav2-open" href="alarmQuery.html">告警追踪查询</a></li> -->'
        +'</ul>'
    +'</li>'
+'</ul>',
	'../nav/businessMonitoring.html':'<ul class="nav nav-stacked text-center">'
    +'<li><a class="content-left-nav1" href="businessSurvey.html">概况</a></li>'
    +'<li><a class="content-left-nav2" href="transactionTrackingQuery.html">交易追踪查询</a></li>'
+'</ul>',
	'../nav/failureDetect.html': '<ul class="nav nav-stacked text-center">'
    +'<li><a class="content-left-nav1" href="failureDetect.html">故障发现</a></li>'
    +'<!--<li><a class="content-left-nav2" href="#">故障定位</a></li>-->'
    +'<li>'
        +'<a class="content-left-nav3 collapsed noCollapsed" data-toggle="collapse" href="#alarmHanding">故障处理</a>'
        +'<ul id="alarmHanding" class="nav nav-list collapse secondmenu">'
            +'<!--<li><a class="content-left-nav3-open1" href="#">告警状态查询</a></li>-->'
            +'<li><a class="content-left-nav3-open2" href="alarmQuery.html">告警追踪查询</a></li>'
        +'</ul>'
    +'</li>'
+'</ul>',
	'../nav/management.html':'<ul class="nav nav-stacked text-center">'
    +'<li><a class="content-left-nav1" href="alarmConf.html">告警配置</a></li>'
    +'<!-- <li><a class="content-left-nav2" href="busiMonitoringConf.html ">业务监控配置</a></li> -->'
+'</ul>',
	'../nav/operationAnalysis.html': '<ul class="nav nav-stacked text-center">'
    +'<li>'
        +'<a class="content-left-nav1 collapsed noCollapsed" data-toggle="collapse" href="#survey">概况</a>'
        +'<ul id="survey" class="nav nav-list collapse secondmenu">'
           +' <!-- <li><a class="content-left-nav1-open" href="submitBusiness.html">提交业务</a></li> -->'
       +' </ul>'
    +'</li>'
	+'<li>'
        +'<a class="content-left-nav2 collapsed noCollapsed" data-toggle="collapse" href="#businessAnalysis">业务分析</a> '
        +'<ul id="businessAnalysis" class="nav nav-list collapse secondmenu">'
            +'<li><a class="content-left-nav1-open" href="keyBusiness.html">重点业务分析</a></li>'
        +'</ul>'
    +'</li>'
+'</ul>'

}